### ISSUE TITLE
xlsheet/google sheet - Not able to get the right information when reading sheets.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#362]
**Steps to reproduce the problem:**
1. Create an agent with xlsheet tool bundle.
2. Ask it to work with the following file -  [Employee Sample Data.xlsx](https://github.com/user-attachments/files/17563877/Employee.Sample.Data.xlsx) and retrieve information about names of the people who work in IT Department by asking - `List the names of people working in IT department from "Employee Sample Data`

I tried to do this in 2. different threads using slightly different prompts.
In both cases, the results returned is incorrect.
It has some entries that are correct,  but most of the entries are are not even present in the xlsheet.

Debug calls for the 2 threads - 
[calls (80).json](https://github.com/user-attachments/files/17563928/calls.80.json)
[calls (79).json](https://github.com/user-attachments/files/17563929/calls.79.json)

**Comment by drpebcak** [comment]
This particular usecase should be resolved, but there are still weaknesses with the tools. if you are working with a spreadsheet that is too large and you do not filter the data enough, you will overwhelm the context window.

**Comment by sangee2004** [comment]
When testing the same scenario with `google sheet` ,  I was able to get the right set of data being returned for the query mentioned in the issues.

When testing with xlsheet , I am still seeing some partial data being returned and then the same entry "Everly Walker" being retruned 4000+ times. 

Debug logs - [calls (13).json](https://github.com/user-attachments/files/17877731/calls.13.json)

**Comment by drpebcak** [comment]
I've just merged in some changes to the excel tools that should make them function more like the sheets tools when it comes to queries like this.

**Comment by sangee2004** [comment]
Tested with latest version of the tool.

Able to see the right results being returned for the query mentioned in the issue.
